### ISSUE TITLE
Source code & Documentation

### ISSUE THREAD

**Issue by ghost** [weijiawu/TextAsLine#1]
@weijiawu Hi,
What is the current status of the code, when do you expect releasing it?
Will you release documentation?

**Comment by weijiawu** [comment]
We proposed a scene text detection method based on weak supervised learning, and the performance of that is close to other full supervised detection method. Therefore, we have finished a paper concerning the work in AAAI2020. We will release relative documentation and code based on the acception result of AAAI2020.

**Comment by ghost** [comment]
@weijiawu 
any updates regarding the code?
